{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Bases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Base RCL Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "base_level_progress", "legendFormat": "{{base}}" }
   ]
  },
  {
   "title": "Bases Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "base_level", "legendFormat": "{{base}}" }
   ]
  },
  {
   "title": "Base Stored Engery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "base_energy_stored", "legendFormat": "{{base}}" }
   ]
  },
  {
   "title": "Base Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "base_rooms_total", "legendFormat": "{{base}}" }
   ]
  },
  {
   "title": "Base Available Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "base_energy_available", "legendFormat": "{{base}}" },
    {
     "expr": "topic_length{topic=\"base_E59N42_distributor\"}",
     "legendFormat": "Topic Size"
    }
   ]
  },
  {
   "title": "Logistics PID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "base_desired_haulers_total", "legendFormat": "Desired haulers" },
    {
     "expr": "creeps_role_total{role=\"hauler\"}",
     "legendFormat": "Current Haulers"
    },
    {
     "expr": "topic_length{topic=\"base_E59N42_hauler\"}",
     "legendFormat": "Haul Topic"
    }
   ]
  },
  { "title": "Creeps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Creeps by Role",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "creeps_role_total", "legendFormat": "{{role}}" }
   ]
  },
  {
   "title": "Creeps by Base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "creeps_base_total", "legendFormat": "{{base}}" }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Time by Process Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "increase(scheduler_cpu_time_total[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  {
   "title": "Process Runs by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "increase(scheduler_processes_running_total[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  {
   "title": "Process terminations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(scheduler_processes_terminated_total[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  {
   "title": "Process Sleeping by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "increase(scheduler_processes_sleeping_total[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  { "title": "Time & CPU ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "CPU Used per Tick",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "increase(cpu_used_total[5m]) / increase(time[5m]) ",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Tick Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "1 / rate(time[5m])", "legendFormat": "{{shard}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "increase(cpu_used_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ticks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    { "expr": "increase(time[5m])", "legendFormat": "__auto" }
   ]
  },
  { "title": "IPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Topic Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    { "expr": "topic_length", "legendFormat": "{{topic}}" }
   ]
  },
  { "title": "Screeps API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Screeps API Rate Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "screeps_api_rate_limit_remaining",
     "legendFormat": "Remaining"
    },
    { "expr": "screeps_api_rate_limit_reset", "legendFormat": "Reset TTL" }
   ]
  }
 ]
}