apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    app: grafana
  name: grafana
  namespace: screeps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        securityContext:
          runAsUser: 0
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
status: {}
