apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana-data
  name: grafana-data
  namespace: screeps
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "openebs-sc-grafana-data"
  resources:
    requests:
      storage: 100Mi
status: {}
