apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scraper
  name: scraper
  namespace: screeps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  strategy: {}
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: ${DOCKER_REPO}/screeps-scraper:${TAG_NAME}
        imagePullPolicy: ""
        resources: {}
        envFrom:
        - secretRef:
            name: scraper-envvars
      imagePullSecrets:
        - name: regcred
