{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "shard", "query": { "query": "label_values(time, shard)" } }
  ]
 },
 "panels": [
  { "title": "Bases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Base RCL Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_level_progress{shard=\"$shard\"}",
     "legendFormat": "{{base}}"
    }
   ]
  },
  {
   "title": "Bases Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "base_level{shard=\"$shard\"}",
     "legendFormat": "{{base}}"
    }
   ]
  },
  {
   "title": "Base Stored Engery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "base_energy_stored{shard=\"$shard\"}",
     "legendFormat": "{{base}}"
    }
   ]
  },
  {
   "title": "Base Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "base_rooms_total{shard=\"$shard\"}",
     "legendFormat": "{{base}}"
    }
   ]
  },
  {
   "title": "Base Available Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "base_energy_available{shard=\"$shard\"}",
     "legendFormat": "{{base}}"
    },
    {
     "expr": "topic_length{topic=\"base_E59N42_distributor\",shard=\"$shard\"}",
     "legendFormat": "Topic Size"
    }
   ]
  },
  {
   "title": "Logistics PID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "base_desired_haulers_total{shard=\"$shard\"}",
     "legendFormat": "Desired haulers"
    },
    {
     "expr": "creeps_role_total{role=\"hauler\", shard=\"$shard\"}",
     "legendFormat": "Current Haulers"
    },
    {
     "expr": "topic_length{topic=\"base_E59N42_hauler\",shard=\"$shard\"}",
     "legendFormat": "Haul Topic"
    }
   ]
  },
  { "title": "Creeps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Creeps by Role",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "creeps_role_total{shard=\"$shard\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Creeps by Base",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "creeps_base_total{shard=\"$shard\"}",
     "legendFormat": "{{base}}"
    }
   ]
  },
  {
   "title": "Spawn Utilization and Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(spawn_busy{shard=\"$shard\"}[5m])",
     "legendFormat": "Busy"
    },
    {
     "expr": "spawn_spawning_role{shard=\"$shard\"}",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "increase(spawn_no_request{shard=\"$shard\"}[5m])",
     "legendFormat": "No Request"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU Time by Process Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(scheduler_cpu_time_total{shard=\"$shard\"}[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  {
   "title": "Process Runs by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "increase(scheduler_processes_running_total{shard=\"$shard\"}[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  {
   "title": "Process terminations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "increase(scheduler_processes_terminated_total{shard=\"$shard\"}[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  {
   "title": "Process Sleeping by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "increase(scheduler_processes_sleeping_total{shard=\"$shard\"}[5m])",
     "legendFormat": "{{process_type}}"
    }
   ]
  },
  { "title": "IPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Topic Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "topic_length{shard=\"$shard\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Time & CPU ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used per Tick",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "increase(cpu_used_total{shard=\"$shard\"}[5m]) / increase(time{shard=\"$shard\"}[5m]) ",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Tick Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "1 / rate(time{shard=\"$shard\"}[5m])",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "increase(cpu_used_total{shard=\"$shard\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ticks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "increase(time{shard=\"$shard\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ticks since start",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "expr": "ticks_since_start{shard=\"$shard\"}",
       "legendFormat": "Ticks since bot start"
      }
     ]
    }
   ]
  },
  {
   "title": "Screeps API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Screeps API Rate Limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "screeps_api_rate_limit_remaining{shard=\"$shard\"}",
       "legendFormat": "Remaining"
      },
      {
       "expr": "screeps_api_rate_limit_reset{shard=\"$shard\"}",
       "legendFormat": "Reset TTL"
      }
     ]
    }
   ]
  }
 ]
}